[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_ignores = True
check_untyped_defs = False

[mypy-openpyxl.*]
ignore_missing_imports = True

[mypy-filelock.*]
ignore_missing_imports = True

[mypy-xlwings.*]
ignore_missing_imports = True

[mypy-win32com.*]
ignore_missing_imports = True

[mypy-pythoncom.*]
ignore_missing_imports = True

[mypy-bsdiff4.*]
ignore_missing_imports = True
