# -*- coding: utf-8 -*-
# Writes xlwings.conf for the local staging tree (dist\CSV_Tool\ etc.).
# Inno Setup: generate the installed file with {app}-based absolute paths instead of this copy.
param(
    [Parameter(Mandatory = $true)]
    [string]$StagingRoot
)

$root = [System.IO.Path]::GetFullPath($StagingRoot)
$runner = Join-Path $root "app\bin\hc_xlwings_short_runner.exe"
$runnerFull = [System.IO.Path]::GetFullPath($runner)

function Line([string]$name, [string]$value) {
    $v = $value
    if ($v -match '\s') { $v = '"' + $v + '"' }
    return "$name = $v"
}

$lines = @(
    '# -*- coding: utf-8 -*-',
    '# Staging: generated by tools\nuitka\assemble_csv_tool_staging.bat',
    '# Paths are absolute on the build machine. For production, Inno Setup should emit',
    '# INTERPRETER_WIN / INTERPRETER pointing at {app}\app\bin\hc_xlwings_short_runner.exe',
    '# and set USE_PACKAGED_RUNPYTHON = True as needed.',
    '',
    (Line 'INTERPRETER_WIN' $runnerFull),
    (Line 'INTERPRETER' $runnerFull),
    'USE_UDF_SERVER = False',
    'DEBUG_UDFS = False',
    '',
    'USE_PACKAGED_RUNPYTHON = True',
    ''
)

$addinDir = Join-Path $root 'addin'
if (-not (Test-Path -LiteralPath $addinDir)) {
    New-Item -ItemType Directory -Path $addinDir | Out-Null
}

$outAddin = Join-Path $addinDir 'xlwings.conf'
$outRoot = Join-Path $root 'xlwings.conf'
$enc = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($outAddin, $lines, $enc)
[System.IO.File]::WriteAllLines($outRoot, $lines, $enc)
Write-Host "Wrote $outAddin"
Write-Host "Wrote $outRoot (compat)"
